server:
  port: 8087
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.86.101
  rabbitmq:
    host: 192.168.86.101
    username: wei
    password: wei
    virtual-host: /
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.leyou.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.leyou: debug