server:
  port: 10010
spring:
  application:
    name: ly-gateway
  redis:
    host: 192.168.86.101
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 6000 # 熔断超时时长：6000ms
ribbon:
  ConnectTimeout: 500 # ribbon链接超时时长
  ReadTimeout: 2000 # ribbon读取超时时长
zuul:
  prefix: /api
  routes:
    item-service: /item/** # 将商品微服务映射到/item/**
    upload-service: /upload/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
  sensitive-headers:
ly:
  jwt:
    pubKeyPath: E:/Course/ssh/id_rsa.pub # C:/develop/ssh/id_rsa.pub # 公钥地址
    user:
      cookieName: LY_TOKEN # cookie名称
  filter:
    allowPaths:
    - "*:/api/auth/login"
    - "*:/api/auth/verify"
    - "*:/api/search/page"
    - "*:/api/search/filter"
    - "*:/api/user/register"
    - "*:/api/user/code"
    - "*:/api/user/check"
    - "Get:/api/item"
