server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: root
  rabbitmq:
    host: 192.168.86.101
    username: wei
    password: wei
    virtual-host: /
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 80000ms
        multiplier: 2
    publisher-confirms: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

mybatis:
  base-packages: com.leyou.item.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml

logging:
  level:
    com.leyou: debug

#  修改关键词冲突问题
mapper:
  wrap-keyword: "`{0}`"